#!/usr/bin/env bash
# Configure domain zone so that the subdomain
#   www points to your load-balancer IP (lb-01)

# Function to query DNS information for a subdomain and display the result
get_domain_info() {
    local domain="$1"
    local subdomain="$2"

    local dns_info
    dns_info=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')
    local record_type
    record_type=$(echo "$dns_info" | awk '/IN\s/{print $4}')
    local destination
    destination=$(echo "$dns_info" | awk '/IN\s/{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script logic
if [ $# -eq 1 ]; then
    get_domain_info "$1" "www"
    get_domain_info "$1" "lb-01"
    get_domain_info "$1" "web-01"
    get_domain_info "$1" "web-02"
elif [ $# -eq 2 ]; then
    get_domain_info "$1" "$2"
else
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi
