#!/usr/bin/env bash
# This script will transfer a file from one server to another.
# Requirements:
# 1. Accepts 4 parameters
#       - Path to the file to be transferred
#       - IP of the server to transfer the file to
#       - Username scp connects with
#       - Path to the SSH private key, scp uses
# 2. Display Usage: 0-transfer_file PATH_TO_FILE IP
#   USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# 3. scp must transfer the file to the user home directory ~/
# 4. Strict host key checking must be disabled when using scp

# check if number of arguments is less than 3
if [ $# -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# use scp to transfer file to server
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip:~/"

# check exit status of scp
if scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip:~/"; then
    echo "File transferred successfully to $server_ip"
else
    echo "File transfer failed"
fi
