#!/usr/bin/env bash
# This script will install nginx web server on an ubuntu server

# update and upgrade ubuntu packages
sudo apt-get update && sudo apt-get -y upgrade

# install nginx
sudo apt-get -y install nginx

# install net-tools
sudo apt-get -y install net-tools

# Creating an index.html file with "Hello World" inside
echo "Hello World!" | sudo tee /var/www/html/index.html

# test nginx configuration
sudo nginx -t

# reload nginx
sudo service nginx reload
