#!/usr/bin/env bash
# configure server with: HAproxy
# install HAproxy on your lb-01 server.
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y haproxy

# HAproxy Server configuration file
haproxy_server_config=\
"
frontend haproxy
    bind *:80
    mode http
    option forwardfor
    default_backend webservers

backend webservers
    balance roundrobin
    server 230812-web-01 100.26.239.234:80 check
    server 230812-web-02 54.236.75.74:80 check
"
echo "$haproxy_server_config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAproxy to start via the init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Backup the original default HAproxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Test configuration file for HAproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart/Reload the service after changes
sudo service haproxy restart
