#!/usr/bin/env bash
# Script configures Nginx to run and listen on port 80
sudo pkill -9 nginx 2>/dev/null && sudo service nginx restart
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
