#!/usr/bin/env bash
# Write a Bash script that displays a list of currently running processes.
# That allows youto get get the PID of your Bash process.
# Requirements:
# You cannot use pgrep
# The third line of your script must be # shellcheck disable=SC2009 (for more info about ignoring shellcheck error here)

ps -auxf | grep bash