#!/usr/bin/env bash
# Script displays content of the file /etc/passwd
# Script only displays username, user_id, and home directory path
# Using while loop

while read -r p; do
    echo "$p" | cut -d ':' -f 1,3,6
done < /etc/passwd
