#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but for the 9th time it will display "Hi"
# using if statement and while loop
counter=0
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done