#!/usr/bin/env bash
# This script loops through 1 to 10
# displays "bad luck" for the 4th loop iteration
# displays "good luck" for the 8th loop iteration
# displays "Best School" for the rest of the loop iterations
# using if, elif, and else statement and while loop

#intialize counter
counter=1

#using while loop
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done