#!/usr/bin/env bash
# Script displays content of the current directory
# in a list format. When the script is run, it should
# display the content of the current directory where
# only the part of the name after the first dash is
# displayed.
# Using a for loop and hidden files are not displayed

# Using for loop, display content of the current directory
files="$(ls)"
for file in $files;
do
    echo "$file" | cut -d '-' -f2
done