#!/usr/bin/env bash
# Script gives info about the school file.

file="school"
# check if the file exists
if [ -e $file ];
then
    echo "school file exists"

    # check if the file is empty
    if [ -s $file ];
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # check if the file is a regular file
    if [ -f $file ];
    then
        echo "school file is a regular file"
    fi
else
    echo "school file does not exist"
fi